In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules,fpgrowth,fpmax

In [2]:
data = pd.read_csv('supermarket.csv')

In [3]:
data.head()

    Customer Id        Date           Product
0  JKML5ZWXP0XQ  2020-07-20    tropical fruit
1  YOGWQIUPDAJ7  2020-04-30        whole milk
2  Q3NL22281AF6  2020-09-18         pip fruit
3  C59GRTLMZQAU  2020-12-11  other vegetables
4  WUSF8LTEQZ5L  2020-01-02        whole milk

In [4]:
# فرض می کنیم خرید هر مشتری در هر روز یک سبد خرید است. لذا ستون جدیدی با عنوان سبد به داده ها اضافه می کنیم
data['Sabad']=data['Customer Id']+data['Date']

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32710 entries, 0 to 32709
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer Id  32710 non-null  object
 1   Date         32710 non-null  object
 2   Product      32710 non-null  object
 3   Sabad        32710 non-null  object
dtypes: object(4)
memory usage: 1022.3+ KB

In [6]:
data.describe()

         Customer Id        Date     Product                   Sabad
count          32710       32710       32710                   32710
unique          3893         728         137                   14753
top     0P1TPIH74E79  2020-01-21  whole milk  DD3KOEOVDVIM2020-04-16
freq              32          80        2363                       9

In [7]:
data2 = data.groupby(['Sabad','Product']).size()
datar = pd.DataFrame(data2).reset_index()
datar.columns = ['Sabad','Product','Count']
datar.head()

                    Sabad          Product  Count
0  0011457U6R3Y2020-10-13      brown bread      1
1  0011457U6R3Y2020-10-13          dessert      1
2  0011457U6R3Y2020-10-13       rolls/buns      1
3  008J5Z3CJPYU2019-01-27            flour      1
4  008J5Z3CJPYU2019-01-27  root vegetables      1

In [8]:
Tdata = (datar.groupby(['Sabad', 'Product'])['Count']
          .sum().unstack().reset_index().fillna(0)
          .set_index('Sabad'))
Tdata.head()

Product,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,tea,toilet cleaner,tropical fruit,turkey,waffles,whipped/sour cream,white bread,whole milk,yogurt,zwieback
Sabad,,,,,,,,,,,,,,,,,,,,,
0011457U6R3Y2020-10-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
008J5Z3CJPYU2019-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
008J5Z3CJPYU2019-06-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
008J5Z3CJPYU2019-10-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
008J5Z3CJPYU2019-10-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [9]:
def hot_encode(x):
    if(x<= 0):
        return 0
    if(x>= 1):
        return 1
 
# Encoding the datasets
Tdata_encoded = Tdata.applymap(hot_encode)
Tdata_encoded.head()

Product,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,tea,toilet cleaner,tropical fruit,turkey,waffles,whipped/sour cream,white bread,whole milk,yogurt,zwieback
Sabad,,,,,,,,,,,,,,,,,,,,,
0011457U6R3Y2020-10-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
008J5Z3CJPYU2019-01-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
008J5Z3CJPYU2019-06-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
008J5Z3CJPYU2019-10-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
008J5Z3CJPYU2019-10-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [10]:
# Building the model
frq_items = apriori(Tdata_encoded, min_support = 0.01, use_colnames = True).sort_values('support', ascending = False)
print(frq_items)

     support                        itemsets
51  0.160171                    (whole milk)
33  0.123839              (other vegetables)
37  0.111571                    (rolls/buns)
42  0.098488                          (soda)
52  0.087101                        (yogurt)
38  0.070562               (root vegetables)
47  0.068732                (tropical fruit)
5   0.061547                 (bottled water)
40  0.061208                       (sausage)
13  0.053887                  (citrus fruit)
34  0.052464                        (pastry)
35  0.049753                     (pip fruit)
4   0.045957                  (bottled beer)
49  0.044330            (whipped/sour cream)
6   0.038162                   (brown bread)
17  0.037619                 (domestic eggs)
7   0.035722                        (butter)
20  0.034501         (fruit/vegetable juice)
1   0.034434                          (beef)
15  0.034163                          (curd)
28  0.032671                     (margarine)
14  0.032061                        (coffee)
19  0.028401             (frozen vegetables)
11  0.028265                       (chicken)
50  0.024334                   (white bread)
12  0.023927                     (chocolate)
16  0.023927                       (dessert)
30  0.022436                       (napkins)
22  0.022165                (hamburger meat)
2   0.022097                       (berries)
0   0.021691                      (UHT-milk)
32  0.020538                        (onions)
39  0.019047                   (salty snack)
48  0.018776                       (waffles)
27  0.018166      (long life bakery product)
46  0.017962                         (sugar)
8   0.017827                   (butter milk)
29  0.017081                          (meat)
18  0.017013                  (frozen meals)
3   0.016810                     (beverages)
45  0.016200           (specialty chocolate)
26  0.015387                     (ice cream)
31  0.015116                           (oil)
54  0.015048  (other vegetables, whole milk)
23  0.014912                   (hard cheese)
21  0.014641                        (grapes)
9   0.014573                         (candy)
41  0.014234                 (sliced cheese)
44  0.014167                 (specialty bar)
55  0.014167        (rolls/buns, whole milk)
25  0.013895              (hygiene articles)
10  0.012201                   (chewing gum)
56  0.011794              (soda, whole milk)
57  0.011320            (yogurt, whole milk)
53  0.010710  (other vegetables, rolls/buns)
24  0.010710                         (herbs)
36  0.010303              (processed cheese)
43  0.010167                   (soft cheese)

In [11]:
# Collecting the inferred rules in a dataframe
rules = association_rules(frq_items, metric ="lift", min_threshold = 0.001)
rules = rules.sort_values(['confidence'], ascending =[False])
print(rules)

          antecedents         consequents  antecedent support  \
6            (yogurt)        (whole milk)            0.087101
2        (rolls/buns)        (whole milk)            0.111571
0  (other vegetables)        (whole milk)            0.123839
4              (soda)        (whole milk)            0.098488
9        (rolls/buns)  (other vegetables)            0.111571
1        (whole milk)  (other vegetables)            0.160171
3        (whole milk)        (rolls/buns)            0.160171
8  (other vegetables)        (rolls/buns)            0.123839
5        (whole milk)              (soda)            0.160171
7        (whole milk)            (yogurt)            0.160171

   consequent support   support  confidence      lift  leverage  conviction
6            0.160171  0.011320    0.129961  0.811391 -0.002631    0.965278
2            0.160171  0.014167    0.126974  0.792744 -0.003704    0.961976
0            0.160171  0.015048    0.121511  0.758632 -0.004788    0.955992
4            0.160171  0.011794    0.119752  0.747653 -0.003981    0.954083
9            0.123839  0.010710    0.095990  0.775120 -0.003107    0.969194
1            0.123839  0.015048    0.093948  0.758632 -0.004788    0.967010
3            0.111571  0.014167    0.088447  0.792744 -0.003704    0.974633
8            0.111571  0.010710    0.086481  0.775120 -0.003107    0.972535
5            0.098488  0.011794    0.073635  0.747653 -0.003981    0.973171
7            0.087101  0.011320    0.070673  0.811391 -0.002631    0.982323